#### XGBOOSTS experiment

In [1]:
# import libraries
import pandas as pd
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.ensemble import StackingClassifier
from sklearn.linear_model import LogisticRegression

In [2]:
df = pd.read_csv('/home/h6x/git_projects/ornl-overdose-modeling-per-images/XGBoost/merged_data.csv')

In [3]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,1491,1492,1493,1494,1495,1496,1497,1498,1499,NOD
0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000,1.514899e-14,3.209290e-10,9.503154e-07,0.000406,0.026770,0.300987,0.646748,2.946155e-01,16.0
1,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000960,6.651963e-02,8.597344e-01,2.214312e+00,1.179606,0.126665,0.002570,0.000009,5.752881e-09,14.3
2,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000,4.662937e-16,1.613967e-11,8.468984e-08,0.000062,0.006613,0.109498,0.307713,1.547352e-01,13.2
3,-9.769201e-19,-9.769201e-19,-9.769201e-19,-9.769201e-19,-9.769201e-19,-9.769201e-19,-9.769201e-19,-9.769201e-19,-9.769201e-19,-9.769201e-19,...,8.803300,5.609908e+00,5.410463e+00,5.710499e+00,11.505115,17.191642,18.429429,19.122997,1.584945e+01,14.5
4,2.029232e-102,2.029232e-102,2.029232e-102,2.029232e-102,2.029232e-102,2.029232e-102,2.029232e-102,2.029232e-102,2.029232e-102,2.029232e-102,...,0.020208,1.340564e-04,5.005771e-03,1.676467e-01,0.971865,1.388327,1.082380,1.385486,6.841777e-01,15.9

In [4]:
# sort the data by NOD
df = df.sort_values(by='NOD', ascending=False)

In [ ]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,1491,1492,1493,1494,1495,1496,1497,1498,1499,NOD
435,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,1.842772e+00,1.325407e+00,0.739708,1.291467,1.203635,0.808255,0.641495,1.024947,0.941729,114.4
412,-6.001313e-54,-6.001313e-54,-6.001313e-54,-6.001313e-54,-6.001313e-54,-6.001313e-54,-6.001313e-54,-6.001313e-54,-6.001313e-54,-6.001313e-54,...,4.377433e+00,4.517206e+00,3.496662,7.511271,12.275541,11.494628,12.035619,13.453358,9.898905,108.8
554,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,1.977013e-10,5.573400e-07,0.000255,0.019633,0.269677,0.709728,0.373932,0.057718,0.061832,94.7
2137,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,9.756763e-01,2.871876e+00,1.810453,0.240114,0.006368,0.003967,0.066061,0.227159,0.167029,85.1
504,9.387543e-76,9.387543e-76,9.387543e-76,9.387543e-76,9.387543e-76,9.387543e-76,9.387543e-76,9.387543e-76,9.387543e-76,9.387543e-76,...,5.136389e+00,6.120937e+00,6.288242,6.971916,7.697489,6.929734,7.009416,7.647796,4.894034,70.9

In [6]:
# add new column to the data frame as a label and by the quantile of NOD add the label
df['label'] = pd.qcut(df['NOD'], q=[0,0.80,1], labels=['0', '1'])

In [7]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,1492,1493,1494,1495,1496,1497,1498,1499,NOD,label
435,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,1.325407e+00,0.739708,1.291467,1.203635,0.808255,0.641495,1.024947,0.941729,114.4,1
412,-6.001313e-54,-6.001313e-54,-6.001313e-54,-6.001313e-54,-6.001313e-54,-6.001313e-54,-6.001313e-54,-6.001313e-54,-6.001313e-54,-6.001313e-54,...,4.517206e+00,3.496662,7.511271,12.275541,11.494628,12.035619,13.453358,9.898905,108.8,1
554,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,5.573400e-07,0.000255,0.019633,0.269677,0.709728,0.373932,0.057718,0.061832,94.7,1
2137,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,2.871876e+00,1.810453,0.240114,0.006368,0.003967,0.066061,0.227159,0.167029,85.1,1
504,9.387543e-76,9.387543e-76,9.387543e-76,9.387543e-76,9.387543e-76,9.387543e-76,9.387543e-76,9.387543e-76,9.387543e-76,9.387543e-76,...,6.120937e+00,6.288242,6.971916,7.697489,6.929734,7.009416,7.647796,4.894034,70.9,1

In [8]:
df_train = df.drop(['NOD'], axis=1)

In [9]:
df_train.head()

,0,1,2,3,4,5,6,7,8,9,...,1491,1492,1493,1494,1495,1496,1497,1498,1499,label
435,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,1.842772e+00,1.325407e+00,0.739708,1.291467,1.203635,0.808255,0.641495,1.024947,0.941729,1
412,-6.001313e-54,-6.001313e-54,-6.001313e-54,-6.001313e-54,-6.001313e-54,-6.001313e-54,-6.001313e-54,-6.001313e-54,-6.001313e-54,-6.001313e-54,...,4.377433e+00,4.517206e+00,3.496662,7.511271,12.275541,11.494628,12.035619,13.453358,9.898905,1
554,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,1.977013e-10,5.573400e-07,0.000255,0.019633,0.269677,0.709728,0.373932,0.057718,0.061832,1
2137,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,9.756763e-01,2.871876e+00,1.810453,0.240114,0.006368,0.003967,0.066061,0.227159,0.167029,1
504,9.387543e-76,9.387543e-76,9.387543e-76,9.387543e-76,9.387543e-76,9.387543e-76,9.387543e-76,9.387543e-76,9.387543e-76,9.387543e-76,...,5.136389e+00,6.120937e+00,6.288242,6.971916,7.697489,6.929734,7.009416,7.647796,4.894034,1

In [10]:
y = df_train['label']

# turn string labels into integers
y = y.astype('int')

In [11]:
# get the first 100 columns as features
x_set_1 = df_train.iloc[:, 0:100]
x_set_2 = df_train.iloc[:, 100:200]
x_set_3 = df_train.iloc[:, 200:300]
x_set_4 = df_train.iloc[:, 300:400]
x_set_5 = df_train.iloc[:, 400:500]
x_set_6 = df_train.iloc[:, 500:600]
x_set_7 = df_train.iloc[:, 600:700]
x_set_8 = df_train.iloc[:, 700:800]
x_set_9 = df_train.iloc[:, 800:900]
x_set_10 = df_train.iloc[:, 900:1000]
x_set_11 = df_train.iloc[:, 1000:1100]
x_set_12 = df_train.iloc[:, 1100:1200]
x_set_13 = df_train.iloc[:, 1200:1300]
x_set_14 = df_train.iloc[:, 1300:1400]
x_set_15 = df_train.iloc[:, 1400:1500]

In [12]:
# Train-test split
X1_train, X1_test, y_train, y_test = train_test_split(x_set_1, y, test_size=0.2, random_state=42)
X2_train, X2_test, _, _ = train_test_split(x_set_2, y, test_size=0.2, random_state=42)
X3_train, X3_test, _, _ = train_test_split(x_set_3, y, test_size=0.2, random_state=42)
X4_train, X4_test, _, _ = train_test_split(x_set_4, y, test_size=0.2, random_state=42)
X5_train, X5_test, _, _ = train_test_split(x_set_5, y, test_size=0.2, random_state=42)
X6_train, X6_test, _, _ = train_test_split(x_set_6, y, test_size=0.2, random_state=42)
X7_train, X7_test, _, _ = train_test_split(x_set_7, y, test_size=0.2, random_state=42)
X8_train, X8_test, _, _ = train_test_split(x_set_8, y, test_size=0.2, random_state=42)
X9_train, X9_test, _, _ = train_test_split(x_set_9, y, test_size=0.2, random_state=42)
X10_train, X10_test, _, _ = train_test_split(x_set_10, y, test_size=0.2, random_state=42)
X11_train, X11_test, _, _ = train_test_split(x_set_11, y, test_size=0.2, random_state=42)
X12_train, X12_test, _, _ = train_test_split(x_set_12, y, test_size=0.2, random_state=42)
X13_train, X13_test, _, _ = train_test_split(x_set_13, y, test_size=0.2, random_state=42)
X14_train, X14_test, _, _ = train_test_split(x_set_14, y, test_size=0.2, random_state=42)
X15_train, X15_test, _, _ = train_test_split(x_set_15, y, test_size=0.2, random_state=42)

In [13]:
# Train individual models
model1 = XGBClassifier().fit(X1_train, y_train)
model2 = XGBClassifier().fit(X2_train, y_train)
model3 = XGBClassifier().fit(X3_train, y_train)
model4 = XGBClassifier().fit(X4_train, y_train)
model5 = XGBClassifier().fit(X5_train, y_train)
model6 = XGBClassifier().fit(X6_train, y_train)
model7 = XGBClassifier().fit(X7_train, y_train)
model8 = XGBClassifier().fit(X8_train, y_train)
model9 = XGBClassifier().fit(X9_train, y_train)
model10 = XGBClassifier().fit(X10_train, y_train)
model11 = XGBClassifier().fit(X11_train, y_train)
model12 = XGBClassifier().fit(X12_train, y_train)
model13 = XGBClassifier().fit(X13_train, y_train)
model14 = XGBClassifier().fit(X14_train, y_train)
model15 = XGBClassifier().fit(X15_train, y_train)

In [14]:
# Predictions
pred1 = model1.predict_proba(X1_test)[:, 1]
pred2 = model2.predict_proba(X2_test)[:, 1]
pred3 = model3.predict_proba(X3_test)[:, 1]
pred4 = model4.predict_proba(X4_test)[:, 1]
pred5 = model5.predict_proba(X5_test)[:, 1]
pred6 = model6.predict_proba(X6_test)[:, 1]
pred7 = model7.predict_proba(X7_test)[:, 1]
pred8 = model8.predict_proba(X8_test)[:, 1]
pred9 = model9.predict_proba(X9_test)[:, 1]
pred10 = model10.predict_proba(X10_test)[:, 1]
pred11 = model11.predict_proba(X11_test)[:, 1]
pred12 = model12.predict_proba(X12_test)[:, 1]
pred13 = model13.predict_proba(X13_test)[:, 1]
pred14 = model14.predict_proba(X14_test)[:, 1]
pred15 = model15.predict_proba(X15_test)[:, 1]

In [15]:
# Combine predictions into a new dataset
meta_X = pd.DataFrame({'pred1': pred1, 'pred2': pred2, 'pred3': pred3, 'pred4': pred4, 'pred5': pred5, 'pred6': pred6, 'pred7': pred7, 'pred8': pred8, 'pred9': pred9, 'pred10': pred10, 'pred11': pred11, 'pred12': pred12, 'pred13': pred13, 'pred14': pred14, 'pred15': pred15})

In [16]:
# train a meta-model on the predictions
meta_model = LogisticRegression().fit(meta_X, y_test)

In [17]:
# Evaluate meta-model
accuracy = meta_model.score(meta_X, y_test)
print(f"Meta-Model Accuracy: {accuracy:.2f}")

Meta-Model Accuracy: 0.80

In [18]:
# get the f1 scores for the meta-model each class
from sklearn.metrics import f1_score

y_pred = meta_model.predict(meta_X)
f1 = f1_score(y_test, y_pred)
print(f"Meta-Model F1 Score: {f1:.2f}")

# get the confusion matrix for the meta-model
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, y_pred)

# get the classification report for the meta-model
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

Meta-Model F1 Score: 0.29
              precision    recall  f1-score   support

           0       0.81      0.97      0.88       429
           1       0.64      0.19      0.29       120

    accuracy                           0.80       549
   macro avg       0.72      0.58      0.59       549
weighted avg       0.77      0.80      0.75       549

In [19]:
# Accessing coefficients of the meta-model
coefficients = meta_model.coef_

# Intercept (bias term)
intercept = meta_model.intercept_

print("Coefficients:", coefficients)
print("Intercept:", intercept)

Coefficients: [[-0.83565703  1.00517352  0.75433123  0.6474557   0.69119889  0.2116771
   1.07483116  0.86261709  0.25858426  0.33919533  0.217761    0.56226028
   1.10266928  0.10532819 -0.20937512]]
Intercept: [-2.41341641]